<?php

namespace Classes\Utils;

class Colors
{
    private $Alpha = false;
    private $BGColor = false;
    private $Color = false;
    private $ColorType = false;
    private $Hex = false;
    private $RGB = false;
    private $Type = false;

    // Public Methods
    public function do($method_name, $data = null, $page = null, $line = null)
    {
        $method = $method_name;

        if (method_exists(__CLASS__, $method)) {
            $bla = __CLASS__;
            return $bla::$method($data);
        }

        echo '<b>ERROR: Class (' . get_called_class() . '):</b><br>';
        echo 'Defined method (' . $method . ') not found!<br>';
        if ($page == null) {
            echo 'Page: N/A<br>';
        } else {
            echo 'Page: ' . $page . '<br>';
        }
        if ($line == null) {
            echo 'Line: N/A<br><br>';
        } else {
            echo 'Line: ' . $line . '<br><br>';
        }
    }

    // Private Methods
    private function doAlpha($data)
    {
        switch ($data) {
            case '0.1':
                return '0.1';
                break;
            case '0.2':
                return '0.2';
                break;
            case '0.25':
                return '0.25';
                break;
            case '0.3':
                return '0.3';
                break;
            case '0.4':
                return '0.4';
                break;
            case '0.5':
                return '0.5';
                break;
            case '0.6':
                return '0.6';
                break;
            case '0.7':
                return '0.7';
                break;
            case '0.8':
                return '0.8';
                break;
            case '0.9':
                return '0.9';
                break;
            case '1':
                return '1';
                break;
            default:
                return $data;
                break;
        }
    }

    private function hex($data)
    {
        switch ($data) {
            case 'AliceBlue':
                return 'F0F8FF';
                break;
            case 'AntiqueWhite':
                return 'FAEBD7';
                break;
            case 'AntiqueWhite1':	return 'FFEFDB';	break;
            case 'AntiqueWhite2':	return 'EEDFCC';	break;
            case 'AntiqueWhite3':	return 'CDC0B0';	break;
            case 'AntiqueWhite4':	return '8B8378';	break;
            case 'Aquamarine':	return '7FFFD4';	break;
            case 'Aquamarine1':	return '7FFFD4';	break;
            case 'Aquamarine2':	return '76EEC6';	break;
            case 'Aquamarine3':	return '66CDAA';	break;
            case 'Aquamarine4':	return '458B74';	break;
            case 'Azure':	return 'F0FFFF';	break;
            case 'Azure1':	return 'F0FFFF';	break;
            case 'Azure2':	return 'E0EEEE';	break;
            case 'Azure3':	return 'C1CDCD';	break;
                case 'Azure4':	return '838B8B';	break;
                case 'Beige':	return 'F5F5DC';	break;
                case 'Bisque':	return 'FFE4C4';	break;
                case 'Bisque1':	return 'FFE4C4';	break;
                case 'Bisque2':	return 'EED5B7';	break;
                case 'Bisque3':	return 'CDB79E';	break;
                case 'Bisque4':	return '8B7D6B';	break;
                case 'Black':	return '000000';	break;
                case 'BlanchedAlmond':	return 'FFEBCD';	break;
                case 'Blue':	return '0000FF';	break;
                case 'Blue1':	return '0000FF';	break;
                case 'Blue2':	return '0000EE';	break;
                case 'Blue3':	return '0000CD';	break;
                case 'Blue4':	return '00008B';	break;
                case 'BlueViolet':	return '8A2BE2';	break;
                case 'Brown':	return 'A52A2A';	break;
                case 'Brown1':	return 'FF4040';	break;
                case 'Brown2':	return 'EE3B3B';	break;
                case 'Brown3':	return 'CD3333';	break;
                case 'Brown4':	return '8B2323';	break;
                case 'Burlywood':	return 'DEB887';	break;
                case 'Burlywood1':	return 'FFD39B';	break;
                case 'Burlywood2':	return 'EEC591';	break;
                case 'Burlywood3':	return 'CDAA7D';	break;
                case 'Burlywood4':	return '8B7355';	break;
                case 'CadetBlue':	return '5F9EA0';	break;
                case 'CadetBlue1':	return '98F5FF';	break;
                case 'CadetBlue2':	return '8EE5EE';	break;
                case 'CadetBlue3':	return '7AC5CD';	break;
                case 'CadetBlue4':	return '53868B';	break;
                case 'Chartreuse':	return '7FFF00';	break;
                case 'Chartreuse1':	return '7FFF00';	break;
                case 'Chartreuse2':	return '76EE00';	break;
                case 'Chartreuse3':	return '66CD00';	break;
                case 'Chartreuse4':	return '458B00';	break;
                case 'Chocolate':	return 'D2691E';	break;
                case 'Chocolate1':	return 'FF7F24';	break;
                case 'Chocolate2':	return 'EE7621';	break;
                case 'Chocolate3':	return 'CD661D';	break;
                case 'Chocolate4':	return '8B4513';	break;
                case 'Coral':	return 'FF7F50';	break;
                case 'Coral1':	return 'FF7256';	break;
                case 'Coral2':	return 'EE6A50';	break;
                case 'Coral3':	return 'CD5B45';	break;
                case 'Coral4':	return '8B3E2F';	break;
                case 'CornflowerBlue':	return '6495ED';	break;
                case 'Cornsilk':	return 'FFF8DC';	break;
                case 'Cornsilk1':	return 'FFF8DC';	break;
                case 'Cornsilk2':	return 'EEE8CD';	break;
                case 'Cornsilk3':	return 'CDC8B1';	break;
                case 'Cornsilk4':	return '8B8878';	break;
                case 'Cyan':	return '00FFFF';	break;
                case 'Cyan1':	return '00FFFF';	break;
                case 'Cyan2':	return '00EEEE';	break;
                case 'Cyan3':	return '00CDCD';	break;
                case 'Cyan4':	return '008B8B';	break;
                case 'DarkBlue':	return '00008B';	break;
                case 'DarkCyan':	return '008B8B';	break;
                case 'DarkGoldenrod':	return 'B8860B';	break;
                case 'DarkGoldenrod1':	return 'FFB90F';	break;
                case 'DarkGoldenrod2':	return 'EEAD0E';	break;
                case 'DarkGoldenrod3':	return 'CD950C';	break;
                case 'DarkGoldenrod4':	return '8B6508';	break;
                case 'DarkGray':	return 'A9A9A9';	break;
                case 'DarkGreen':	return '006400';	break;
                case 'DarkKhaki':	return 'BDB76B';	break;
                case 'DarkMagenta':	return '8B008B';	break;
                case 'DarkOliveGreen':	return '556B2F';	break;
                case 'DarkOliveGreen1':	return 'CAFF70';	break;
                case 'DarkOliveGreen2':	return 'BCEE68';	break;
                case 'DarkOliveGreen3':	return 'A2CD5A';	break;
                case 'DarkOliveGreen4':	return '6E8B3D';	break;
                case 'DarkOrange':	return 'FF8C00';	break;
                case 'DarkOrange1':	return 'FF7F00';	break;
                case 'DarkOrange2':	return 'EE7600';	break;
                case 'DarkOrange3':	return 'CD6600';	break;
                case 'DarkOrange4':	return '8B4500';	break;
                case 'DarkOrchid':	return '9932CC';	break;
                case 'DarkOrchid1':	return 'BF3EFF';	break;
                case 'DarkOrchid2':	return 'B23AEE';	break;
                case 'DarkOrchid3':	return '9A32CD';	break;
                case 'DarkOrchid4':	return '68228B';	break;
                case 'DarkRed':	return '8B0000';	break;
                case 'DarkSalmon':	return 'E9967A';	break;
                case 'DarkSeaGreen':	return '8FBC8F';	break;
                case 'DarkSeaGreen1':	return 'C1FFC1';	break;
                case 'DarkSeaGreen2':	return 'B4EEB4';	break;
                case 'DarkSeaGreen3':	return '9BCD9B';	break;
                case 'DarkSeaGreen4':	return '698B69';	break;
                case 'DarkSlateBlue':	return '483D8B';	break;
                case 'DarkSlateGray':	return '2F4F4F';	break;
                case 'DarkSlateGray1':	return '97FFFF';	break;
                case 'DarkSlateGray2':	return '8DEEEE';	break;
                case 'DarkSlateGray3':	return '79CDCD';	break;
                case 'DarkSlateGray4':	return '528B8B';	break;
                case 'DarkTurquoise':	return '00CED1';	break;
                case 'DarkViolet':	return '9400D3';	break;
                case 'DeepPink':	return 'FF1493';	break;
                case 'DeepPink1':	return 'FF1493';	break;
                case 'DeepPink2':	return 'EE1289';	break;
                case 'DeepPink3':	return 'CD1076';	break;
                case 'DeepPink4':	return '8B0A50';	break;
                case 'DeepSkyBlue':	return '00BFFF';	break;
                case 'DeepSkyBlue1':	return '00BFFF';	break;
                case 'DeepSkyBlue2':	return '00B2EE';	break;
                case 'DeepSkyBlue3':	return '009ACD';	break;
                case 'DeepSkyBlue4':	return '00688B';	break;
                case 'DimGray':	return '696969';	break;
                case 'DodgerBlue':	return '1E90FF';	break;
                case 'DodgerBlue1':	return '1E90FF';	break;
                case 'DodgerBlue2':	return '1C86EE';	break;
                case 'DodgerBlue3':	return '1874CD';	break;
                case 'DodgerBlue4':	return '104E8B';	break;
                case 'Firebrick':	return 'B22222';	break;
                case 'Firebrick1':	return 'FF3030';	break;
                case 'Firebrick2':	return 'EE2C2C';	break;
                case 'Firebrick3':	return 'CD2626';	break;
                case 'Firebrick4':	return '8B1A1A';	break;
                case 'FloralWhite':	return 'FFFAF0';	break;
                case 'ForestGreen':	return '228B22';	break;
                case 'Gainsboro':	return 'DCDCDC';	break;
                case 'GhostWhite':	return 'F8F8FF';	break;
                case 'Gold':	return 'FFD700';	break;
                case 'Gold1':	return 'FFD700';	break;
                case 'Gold2':	return 'EEC900';	break;
                case 'Gold3':	return 'CDAD00';	break;
                case 'Gold4':	return '8B7500';	break;
                case 'Goldenrod':	return 'DAA520';	break;
                case 'Goldenrod1':	return 'FFC125';	break;
                case 'Goldenrod2':	return 'EEB422';	break;
                case 'Goldenrod3':	return 'CD9B1D';	break;
                case 'Goldenrod4':	return '8B6914';	break;
                case 'Gray':	return 'BEBEBE';	break;
                case 'Gray0':	return '000000';	break;
                case 'Gray1':	return '030303';	break;
                case 'Gray10':	return '1A1A1A';	break;
                case 'Gray100':	return 'FFFFFF';	break;
                case 'Gray11':	return '1C1C1C';	break;
                case 'Gray12':	return '1F1F1F';	break;
                case 'Gray13':	return '212121';	break;
                case 'Gray14':	return '242424';	break;
                case 'Gray15':	return '262626';	break;
                case 'Gray16':	return '292929';	break;
                case 'Gray17':	return '2B2B2B';	break;
                case 'Gray18':	return '2E2E2E';	break;
                case 'Gray19':	return '303030';	break;
                case 'Gray2':	return '050505';	break;
                case 'Gray20':	return '333333';	break;
                case 'Gray21':	return '363636';	break;
                case 'Gray22':	return '383838';	break;
                case 'Gray23':	return '3B3B3B';	break;
                case 'Gray24':	return '3D3D3D';	break;
                case 'Gray25':	return '404040';	break;
                case 'Gray26':	return '424242';	break;
                case 'Gray27':	return '454545';	break;
                case 'Gray28':	return '474747';	break;
                case 'Gray29':	return '4A4A4A';	break;
                case 'Gray3':	return '080808';	break;
                case 'Gray30':	return '4D4D4D';	break;
                case 'Gray31':	return '4F4F4F';	break;
                case 'Gray32':	return '525252';	break;
                case 'Gray33':	return '545454';	break;
                case 'Gray34':	return '575757';	break;
                case 'Gray35':	return '595959';	break;
                case 'Gray36':	return '5C5C5C';	break;
                case 'Gray37':	return '5E5E5E';	break;
                case 'Gray38':	return '616161';	break;
                case 'Gray39':	return '636363';	break;
                case 'Gray4':	return '0A0A0A';	break;
                case 'Gray40':	return '666666';	break;
                case 'Gray41':	return '696969';	break;
                case 'Gray42':	return '6B6B6B';	break;
                case 'Gray43':	return '6E6E6E';	break;
                case 'Gray44':	return '707070';	break;
                case 'Gray45':	return '737373';	break;
                case 'Gray46':	return '757575';	break;
                case 'Gray47':	return '787878';	break;
                case 'Gray48':	return '7A7A7A';	break;
                case 'Gray49':	return '7D7D7D';	break;
                case 'Gray5':	return '0D0D0D';	break;
                case 'Gray50':	return '7F7F7F';	break;
                case 'Gray51':	return '828282';	break;
                case 'Gray52':	return '858585';	break;
                case 'Gray53':	return '878787';	break;
                case 'Gray54':	return '8A8A8A';	break;
                case 'Gray55':	return '8C8C8C';	break;
                case 'Gray56':	return '8F8F8F';	break;
                case 'Gray57':	return '919191';	break;
                case 'Gray58':	return '949494';	break;
                case 'Gray59':	return '969696';	break;
                case 'Gray6':	return '0F0F0F';	break;
                case 'Gray60':	return '999999';	break;
                case 'Gray61':	return '9C9C9C';	break;
                case 'Gray62':	return '9E9E9E';	break;
                case 'Gray63':	return 'A1A1A1';	break;
                case 'Gray64':	return 'A3A3A3';	break;
                case 'Gray65':	return 'A6A6A6';	break;
                case 'Gray66':	return 'A8A8A8';	break;
                case 'Gray67':	return 'ABABAB';	break;
                case 'Gray68':	return 'ADADAD';	break;
                case 'Gray69':	return 'B0B0B0';	break;
                case 'Gray7':	return '121212';	break;
                case 'Gray70':	return 'B3B3B3';	break;
                case 'Gray71':	return 'B5B5B5';	break;
                case 'Gray72':	return 'B8B8B8';	break;
                case 'Gray73':	return 'BABABA';	break;
                case 'Gray74':	return 'BDBDBD';	break;
                case 'Gray75':	return 'BFBFBF';	break;
                case 'Gray76':	return 'C2C2C2';	break;
                case 'Gray77':	return 'C4C4C4';	break;
                case 'Gray78':	return 'C7C7C7';	break;
                case 'Gray79':	return 'C9C9C9';	break;
                case 'Gray8':	return '141414';	break;
                case 'Gray80':	return 'CCCCCC';	break;
                case 'Gray81':	return 'CFCFCF';	break;
                case 'Gray82':	return 'D1D1D1';	break;
                case 'Gray83':	return 'D4D4D4';	break;
                case 'Gray84':	return 'D6D6D6';	break;
                case 'Gray85':	return 'D9D9D9';	break;
                case 'Gray86':	return 'DBDBDB';	break;
                case 'Gray87':	return 'DEDEDE';	break;
                case 'Gray88':	return 'E0E0E0';	break;
                case 'Gray89':	return 'E3E3E3';	break;
                case 'Gray9':	return '171717';	break;
                case 'Gray90':	return 'E5E5E5';	break;
                case 'Gray91':	return 'E8E8E8';	break;
                case 'Gray92':	return 'EBEBEB';	break;
                case 'Gray93':	return 'EDEDED';	break;
                case 'Gray94':	return 'F0F0F0';	break;
                case 'Gray95':	return 'F2F2F2';	break;
                case 'Gray96':	return 'F5F5F5';	break;
                case 'Gray97':	return 'F7F7F7';	break;
                case 'Gray98':	return 'FAFAFA';	break;
                case 'Gray99':	return 'FCFCFC';	break;
                case 'Green':	return '00FF00';	break;
                case 'Green1':	return '00FF00';	break;
                case 'Green2':	return '00EE00';	break;
                case 'Green3':	return '00CD00';	break;
                case 'Green4':	return '008B00';	break;
                case 'GreenYellow':	return 'ADFF2F';	break;
                case 'Honeydew':	return 'F0FFF0';	break;
                case 'Honeydew1':	return 'F0FFF0';	break;
                case 'Honeydew2':	return 'E0EEE0';	break;
                case 'Honeydew3':	return 'C1CDC1';	break;
                case 'Honeydew4':	return '838B83';	break;
                case 'HotPink':	return 'FF69B4';	break;
                case 'HotPink1':	return 'FF6EB4';	break;
                case 'HotPink2':	return 'EE6AA7';	break;
                case 'HotPink3':	return 'CD6090';	break;
                case 'HotPink4':	return '8B3A62';	break;
                case 'IndianRed1':	return 'FF6A6A';	break;
                case 'IndianRed2':	return 'EE6363';	break;
                case 'IndianRed3':	return 'CD5555';	break;
                case 'IndianRed4':	return '8B3A3A';	break;
                case 'Ivory':	return 'FFFFF0';	break;
                case 'Ivory1':	return 'FFFFF0';	break;
                case 'Ivory2':	return 'EEEEE0';	break;
                case 'Ivory3':	return 'CDCDC1';	break;
                case 'Ivory4':	return '8B8B83';	break;
                case 'Khaki':	return 'F0E68C';	break;
                case 'Khaki1':	return 'FFF68F';	break;
                case 'Khaki2':	return 'EEE685';	break;
                case 'Khaki3':	return 'CDC673';	break;
                case 'Khaki4':	return '8B864E';	break;
                case 'Lavender':	return 'E6E6FA';	break;
                case 'LavenderBlush':	return 'FFF0F5';	break;
                case 'LavenderBlush1':	return 'FFF0F5';	break;
                case 'LavenderBlush2':	return 'EEE0E5';	break;
                case 'LavenderBlush3':	return 'CDC1C5';	break;
                case 'LavenderBlush4':	return '8B8386';	break;
                case 'LawnGreen':	return '7CFC00';	break;
                case 'LemonChiffon':	return 'FFFACD';	break;
                case 'LemonChiffon1':	return 'FFFACD';	break;
                case 'LemonChiffon2':	return 'EEE9BF';	break;
                case 'LemonChiffon3':	return 'CDC9A5';	break;
                case 'LemonChiffon4':	return '8B8970';	break;
                case 'LightBlue':	return 'ADD8E6';	break;
                case 'LightBlue1':	return 'BFEFFF';	break;
                case 'LightBlue2':	return 'B2DFEE';	break;
                case 'LightBlue3':	return '9AC0CD';	break;
                case 'LightBlue4':	return '68838B';	break;
                case 'LightCoral':	return 'F08080';	break;
                case 'LightCyan':	return 'E0FFFF';	break;
                case 'LightCyan1':	return 'E0FFFF';	break;
                case 'LightCyan2':	return 'D1EEEE';	break;
                case 'LightCyan3':	return 'B4CDCD';	break;
                case 'LightCyan4':	return '7A8B8B';	break;
                case 'LightGoldenrod':	return 'EEDD82';	break;
                case 'LightGoldenrod1':	return 'FFEC8B';	break;
                case 'LightGoldenrod2':	return 'EEDC82';	break;
                case 'LightGoldenrod3':	return 'CDBE70';	break;
                case 'LightGoldenrod4':	return '8B814C';	break;
                case 'LightGoldenrodYellow':	return 'FAFAD2';	break;
                case 'LightGray':	return 'D3D3D3';	break;
                case 'LightGreen':	return '90EE90';	break;
                case 'LightPink':	return 'FFB6C1';	break;
                case 'LightPink1':	return 'FFAEB9';	break;
                case 'LightPink2':	return 'EEA2AD';	break;
                case 'LightPink3':	return 'CD8C95';	break;
                case 'LightPink4':	return '8B5F65';	break;
                case 'LightSalmon':	return 'FFA07A';	break;
                case 'LightSalmon1':	return 'FFA07A';	break;
                case 'LightSalmon2':	return 'EE9572';	break;
                case 'LightSalmon3':	return 'CD8162';	break;
                case 'LightSalmon4':	return '8B5742';	break;
                case 'LightSeaGreen':	return '20B2AA';	break;
                case 'LightSkyBlue':	return '87CEFA';	break;
                case 'LightSkyBlue1':	return 'B0E2FF';	break;
                case 'LightSkyBlue2':	return 'A4D3EE';	break;
                case 'LightSkyBlue3':	return '8DB6CD';	break;
                case 'LightSkyBlue4':	return '607B8B';	break;
                case 'LightSlateBlue':	return '8470FF';	break;
                case 'LightSlateGray':	return '778899';	break;
                case 'LightSteelBlue':	return 'B0C4DE';	break;
                case 'LightSteelBlue1':	return 'CAE1FF';	break;
                case 'LightSteelBlue2':	return 'BCD2EE';	break;
                case 'LightSteelBlue3':	return 'A2B5CD';	break;
                case 'LightSteelBlue4':	return '6E7B8B';	break;
                case 'LightYellow':	return 'FFFFE0';	break;
                case 'LightYellow1':	return 'FFFFE0';	break;
                case 'LightYellow2':	return 'EEEED1';	break;
                case 'LightYellow3':	return 'CDCDB4';	break;
                case 'LightYellow4':	return '8B8B7A';	break;
                case 'LimeGreen':	return '32CD32';	break;
                case 'Linen':	return 'FAF0E6';	break;
                case 'Magenta':	return 'FF00FF';	break;
                case 'Magenta1':	return 'FF00FF';	break;
                case 'Magenta2':	return 'EE00EE';	break;
                case 'Magenta3':	return 'CD00CD';	break;
                case 'Magenta4':	return '8B008B';	break;
                case 'Maroon':	return 'B03060';	break;
                case 'Maroon1':	return 'FF34B3';	break;
                case 'Maroon2':	return 'EE30A7';	break;
                case 'Maroon3':	return 'CD2990';	break;
                case 'Maroon4':	return '8B1C62';	break;
                case 'MediumAquamarine':	return '66CDAA';	break;
                case 'MediumBlue':	return '0000CD';	break;
                case 'MediumOrchid':	return 'BA55D3';	break;
                case 'MediumOrchid1':	return 'E066FF';	break;
                case 'MediumOrchid2':	return 'D15FEE';	break;
                case 'MediumOrchid3':	return 'B452CD';	break;
                case 'MediumOrchid4':	return '7A378B';	break;
                case 'MediumPurple':	return '9370DB';	break;
                case 'MediumPurple1':	return 'AB82FF';	break;
                case 'MediumPurple2':	return '9F79EE';	break;
                case 'MediumPurple3':	return '8968CD';	break;
                case 'MediumPurple4':	return '5D478B';	break;
                case 'MediumSeaGreen':	return '3CB371';	break;
                case 'MediumSlateBlue':	return '7B68EE';	break;
                case 'MediumSpringGreen':	return '00FA9A';	break;
                case 'MediumTurquoise':	return '48D1CC';	break;
                case 'MediumVioletRed':	return 'C71585';	break;
                case 'MidnightBlue':	return '191970';	break;
                case 'MintCream':	return 'F5FFFA';	break;
                case 'MistyRose':	return 'FFE4E1';	break;
                case 'MistyRose1':	return 'FFE4E1';	break;
                case 'MistyRose2':	return 'EED5D2';	break;
                case 'MistyRose3':	return 'CDB7B5';	break;
                case 'MistyRose4':	return '8B7D7B';	break;
                case 'Moccasin':	return 'FFE4B5';	break;
                case 'NavajoWhite':	return 'FFDEAD';	break;
                case 'NavajoWhite1':	return 'FFDEAD';	break;
                case 'NavajoWhite2':	return 'EECFA1';	break;
                case 'NavajoWhite3':	return 'CDB38B';	break;
                case 'NavajoWhite4':	return '8B795E';	break;
                case 'NavyBlue':	return '000080';	break;
                case 'OldLace':	return 'FDF5E6';	break;
                case 'OliveDrab':	return '6B8E23';	break;
                case 'OliveDrab1':	return 'C0FF3E';	break;
                case 'OliveDrab2':	return 'B3EE3A';	break;
                case 'OliveDrab3':	return '9ACD32';	break;
                case 'OliveDrab4':	return '698B22';	break;
                case 'Orange':	return 'FFA500';	break;
                case 'Orange1':	return 'FFA500';	break;
                case 'Orange2':	return 'EE9A00';	break;
                case 'Orange3':	return 'CD8500';	break;
                case 'Orange4':	return '8B5A00';	break;
                case 'OrangeRed':	return 'FF4500';	break;
                case 'OrangeRed1':	return 'FF4500';	break;
                case 'OrangeRed2':	return 'EE4000';	break;
                case 'OrangeRed3':	return 'CD3700';	break;
                case 'OrangeRed4':	return '8B2500';	break;
                case 'Orchid':	return 'DA70D6';	break;
                case 'Orchid1':	return 'FF83FA';	break;
                case 'Orchid2':	return 'EE7AE9';	break;
                case 'Orchid3':	return 'CD69C9';	break;
                case 'Orchid4':	return '8B4789';	break;
                case 'PaleGoldenrod':	return 'EEE8AA';	break;
                case 'PaleGreen':	return '98FB98';	break;
                case 'PaleGreen1':	return '9AFF9A';	break;
                case 'PaleGreen2':	return '90EE90';	break;
                case 'PaleGreen3':	return '7CCD7C';	break;
                case 'PaleGreen4':	return '548B54';	break;
                case 'PaleTurquoise':	return 'AFEEEE';	break;
                case 'PaleTurquoise1':	return 'BBFFFF';	break;
                case 'PaleTurquoise2':	return 'AEEEEE';	break;
                case 'PaleTurquoise3':	return '96CDCD';	break;
                case 'PaleTurquoise4':	return '668B8B';	break;
                case 'PaleVioletRed':	return 'DB7093';	break;
                case 'PaleVioletRed1':	return 'FF82AB';	break;
                case 'PaleVioletRed2':	return 'EE799F';	break;
                case 'PaleVioletRed3':	return 'CD6889';	break;
                case 'PaleVioletRed4':	return '8B475D';	break;
                case 'PapayaWhip':	return 'FFEFD5';	break;
                case 'PeachPuff':	return 'FFDAB9';	break;
                case 'PeachPuff1':	return 'FFDAB9';	break;
                case 'PeachPuff2':	return 'EECBAD';	break;
                case 'PeachPuff3':	return 'CDAF95';	break;
                case 'PeachPuff4':	return '8B7765';	break;
                case 'Peru':	return 'CD853F';	break;
                case 'Pink':	return 'FFC0CB';	break;
                case 'Pink1':	return 'FFB5C5';	break;
                case 'Pink2':	return 'EEA9B8';	break;
                case 'Pink3':	return 'CD919E';	break;
                case 'Pink4':	return '8B636C';	break;
                case 'Plum':	return 'DDA0DD';	break;
                case 'Plum1':	return 'FFBBFF';	break;
                case 'Plum2':	return 'EEAEEE';	break;
                case 'Plum3':	return 'CD96CD';	break;
                case 'Plum4':	return '8B668B';	break;
                case 'PowderBlue':	return 'B0E0E6';	break;
                case 'Purple':	return 'A020F0';	break;
                case 'Purple1':	return '9B30FF';	break;
                case 'Purple2':	return '912CEE';	break;
                case 'Purple3':	return '7D26CD';	break;
                case 'Purple4':	return '551A8B';	break;
                case 'Red':	return 'FF0000';	break;
                case 'Red1':	return 'FF0000';	break;
                case 'Red2':	return 'EE0000';	break;
                case 'Red3':	return 'CD0000';	break;
                case 'Red4':	return '8B0000';	break;
                case 'RosyBrown':	return 'BC8F8F';	break;
                case 'RosyBrown1':	return 'FFC1C1';	break;
                case 'RosyBrown2':	return 'EEB4B4';	break;
                case 'RosyBrown3':	return 'CD9B9B';	break;
                case 'RosyBrown4':	return '8B6969';	break;
                case 'RoyalBlue':	return '4169E1';	break;
                case 'RoyalBlue1':	return '4876FF';	break;
                case 'RoyalBlue2':	return '436EEE';	break;
                case 'RoyalBlue3':	return '3A5FCD';	break;
                case 'RoyalBlue4':	return '27408B';	break;
                case 'SaddleBrown':	return '8B4513';	break;
                case 'Salmon':	return 'FA8072';	break;
                case 'Salmon1':	return 'FF8C69';	break;
                case 'Salmon2':	return 'EE8262';	break;
                case 'Salmon3':	return 'CD7054';	break;
                case 'Salmon4':	return '8B4C39';	break;
                case 'SandyBrown':	return 'F4A460';	break;
                case 'SeaGreen':	return '2E8B57';	break;
                case 'SeaGreen1':	return '54FF9F';	break;
                case 'SeaGreen2':	return '4EEE94';	break;
                case 'SeaGreen3':	return '43CD80';	break;
                case 'SeaGreen4':	return '2E8B57';	break;
                case 'Seashell':	return 'FFF5EE';	break;
                case 'Seashell1':	return 'FFF5EE';	break;
                case 'Seashell2':	return 'EEE5DE';	break;
                case 'Seashell3':	return 'CDC5BF';	break;
                case 'Seashell4':	return '8B8682';	break;
                case 'Sienna':	return 'A0522D';	break;
                case 'Sienna1':	return 'FF8247';	break;
                case 'Sienna2':	return 'EE7942';	break;
                case 'Sienna3':	return 'CD6839';	break;
                case 'Sienna4':	return '8B4726';	break;
                case 'SkyBlue':	return '87CEEB';	break;
                case 'SkyBlue1':	return '87CEFF';	break;
                case 'SkyBlue2':	return '7EC0EE';	break;
                case 'SkyBlue3':	return '6CA6CD';	break;
                case 'SkyBlue4':	return '4A708B';	break;
                case 'SlateBlue':	return '6A5ACD';	break;
                case 'SlateBlue1':	return '836FFF';	break;
                case 'SlateBlue2':	return '7A67EE';	break;
                case 'SlateBlue3':	return '6959CD';	break;
                case 'SlateBlue4':	return '473C8B';	break;
                case 'SlateGray':	return '708090';	break;
                case 'SlateGray1':	return 'C6E2FF';	break;
                case 'SlateGray2':	return 'B9D3EE';	break;
                case 'SlateGray3':	return '9FB6CD';	break;
                case 'SlateGray4':	return '6C7B8B';	break;
                case 'Snow':	return 'FFFAFA';	break;
                case 'Snow1':	return 'FFFAFA';	break;
                case 'Snow2':	return 'EEE9E9';	break;
                case 'Snow3':	return 'CDC9C9';	break;
                case 'Snow4':	return '8B8989';	break;
                case 'SpringGreen':	return '00FF7F';	break;
                case 'SpringGreen1':	return '00FF7F';	break;
                case 'SpringGreen2':	return '00EE76';	break;
                case 'SpringGreen3':	return '00CD66';	break;
                case 'SpringGreen4':	return '008B45';	break;
                case 'SteelBlue':	return '4682B4';	break;
                case 'SteelBlue1':	return '63B8FF';	break;
                case 'SteelBlue2':	return '5CACEE';	break;
                case 'SteelBlue3':	return '4F94CD';	break;
                case 'SteelBlue4':	return '36648B';	break;
                case 'Tan':	return 'D2B48C';	break;
                case 'Tan1':	return 'FFA54F';	break;
                case 'Tan2':	return 'EE9A49';	break;
                case 'Tan3':	return 'CD853F';	break;
                case 'Tan4':	return '8B5A2B';	break;
                case 'Thistle':	return 'D8BFD8';	break;
                case 'Thistle1':	return 'FFE1FF';	break;
                case 'Thistle2':	return 'EED2EE';	break;
                case 'Thistle3':	return 'CDB5CD';	break;
                case 'Thistle4':	return '8B7B8B';	break;
                case 'Tomato':	return 'FF6347';	break;
                case 'Tomato1':	return 'FF6347';	break;
                case 'Tomato2':	return 'EE5C42';	break;
                case 'Tomato3':	return 'CD4F39';	break;
                case 'Tomato4':	return '8B3626';	break;
                case 'Turquoise':	return '40E0D0';	break;
                case 'Turquoise1':	return '00F5FF';	break;
                case 'Turquoise2':	return '00E5EE';	break;
                case 'Turquoise3':	return '00C5CD';	break;
                case 'Turquoise4':	return '00868B';	break;
                case 'Violet':	return 'EE82EE';	break;
                case 'VioletRed':	return 'D02090';	break;
                case 'VioletRed1':	return 'FF3E96';	break;
                case 'VioletRed2':	return 'EE3A8C';	break;
                case 'VioletRed3':	return 'CD3278';	break;
                case 'VioletRed4':	return '8B2252';	break;
                case 'Wheat':	return 'F5DEB3';	break;
                case 'Wheat1':	return 'FFE7BA';	break;
                case 'Wheat2':	return 'EED8AE';	break;
                case 'Wheat3':	return 'CDBA96';	break;
                case 'Wheat4':	return '8B7E66';	break;
                case 'White':	return 'FFFFFF';	break;
                case 'WhiteSmoke':	return 'F5F5F5';	break;
                case 'Yellow1':	return 'FFFF00';	break;
                case 'Yellow2':	return 'EEEE00';	break;
                case 'Yellow3':	return 'CDCD00';	break;
                case 'Yellow4':	return '8B8B00';	break;
                case 'YellowGreen':	return '9ACD32';	break;
            }
    }

    private function rgb($data)
    {
        //
    }
}
